# Generated by Django 6.1.1 on 2026-09-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(default=1)),
                ('available_quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'พร้อมใช้งาน'), ('maintenance', 'ส่งซ่อม'), ('out_of_stock', 'หมด')], default='available', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
