# Generated by Django 6.1.1 on 2026-09-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'อุปกรณ์', 'verbose_name_plural': 'รายการอุปกรณ์'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='image_url',
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ซีเรียลนัมเบอร์/รหัส'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='available_quantity',
            field=models.IntegerField(default=1, verbose_name='จำนวนที่คงเหลือ'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(max_length=100, verbose_name='หมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ชื่ออุปกรณ์'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(default='พร้อมใช้งาน', max_length=50, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='total_quantity',
            field=models.IntegerField(default=1, verbose_name='จำนวนทั้งหมด'),
        ),
    ]
